### ISSUE TITLE
提供一个使用国内源的knative安装yml

### ISSUE THREAD

**Issue by wayneliu0019** [OpenCSGs/CSGHub-helm#1]
默认的knative相关组件是指向gcr.io地址的，国内用户没有科学上网情况下，无法正常安装，最好能够提供一个`稳定的使用国内源的knative相关组件的yml或者chart`

**Comment by MasonXon** [comment]
This is indeed a good idea. I will try to create a yaml file that is easy to deploy in the next two days.
